name: Release

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-plz:
    uses: joshka/github-workflows/.github/workflows/rust-release-plz.yml@main
    permissions:
      pull-requests: write
      contents: write
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
