name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: joshka/github-workflows/.github/workflows/rust-test.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
